Repository jtenner/as-pect, pull requests merged in 2019-06, with the labels that each got.

#97 Moved back to named exports
  __tests__/TestResult.spec.ts
  lib/as-pect.amd.d.ts
  lib/as-pect.amd.d.ts.map
  lib/as-pect.amd.js
  lib/as-pect.amd.js.map
  lib/cli/run.js
  lib/cli/run.js.map
  lib/cli/util/collectReporter.js
  lib/cli/util/collectReporter.js.map
  lib/reporter/CSVTestReporter.d.ts
  lib/reporter/CSVTestReporter.d.ts.map
  lib/reporter/CSVTestReporter.js
  lib/reporter/CSVTestReporter.js.map
  lib/reporter/DefaultTestReporter.d.ts
  lib/reporter/DefaultTestReporter.d.ts.map
  lib/reporter/DefaultTestReporter.js
  lib/reporter/DefaultTestReporter.js.map
  lib/reporter/EmptyReporter.d.ts
  lib/reporter/EmptyReporter.d.ts.map
  lib/reporter/EmptyReporter.js
  lib/reporter/EmptyReporter.js.map
  lib/reporter/JSONTestReporter.d.ts
  lib/reporter/JSONTestReporter.d.ts.map
  lib/reporter/JSONTestReporter.js
  lib/reporter/JSONTestReporter.js.map
  lib/reporter/SummaryTestReporter.d.ts
  lib/reporter/SummaryTestReporter.d.ts.map
  lib/reporter/SummaryTestReporter.js
  lib/reporter/SummaryTestReporter.js.map
  lib/test/TestContext.js
  lib/test/TestContext.js.map
  src/cli/run.ts
  src/cli/util/collectReporter.ts
  src/reporter/CSVTestReporter.ts
  src/reporter/DefaultTestReporter.ts
  src/reporter/EmptyReporter.ts
  src/reporter/JSONTestReporter.ts
  src/reporter/SummaryTestReporter.ts
  src/test/TestContext.ts
Labels: enhancement

#98 TestGroup parent support
  assembly/__tests__/RTrace.spec.wat
  assembly/__tests__/addedFiles.spec.wat
  assembly/__tests__/customImports.spec.wat
  assembly/__tests__/empty.spec.wat
  assembly/__tests__/emptyDescribeBlock.spec.wat
  assembly/__tests__/flow.spec.wat
  assembly/__tests__/greaterThan.spec.wat
  assembly/__tests__/greaterThanOrEqualTo.spec.wat
  assembly/__tests__/lessThan.spec.wat
  assembly/__tests__/lessThanOrEqualTo.spec.wat
  assembly/__tests__/logs.spec.wat
  assembly/__tests__/nested-describe.spec.wat
  assembly/__tests__/performance.spec.wat
  assembly/__tests__/toBe.spec.wat
  assembly/__tests__/toBeCloseTo.spec.wat
  assembly/__tests__/toBeFalsy.spec.wat
  assembly/__tests__/toBeFinite.spec.wat
  assembly/__tests__/toBeNaN.spec.wat
  assembly/__tests__/toBeNull.spec.wat
  assembly/__tests__/toBeTruthy.spec.wat
  assembly/__tests__/toHaveLength.spec.wat
  assembly/__tests__/toInclude.spec.wat
  assembly/__tests__/toIncludeEqual.spec.wat
  assembly/__tests__/toStrictEqual.spec.wat
  assembly/__tests__/unit.spec.wat
  assembly/__tests__/unreachable.spec.wat
  lib/as-pect.amd.d.ts
  lib/as-pect.amd.d.ts.map
  lib/as-pect.amd.js
  lib/as-pect.amd.js.map
  lib/cli/util/collectReporter.js
  lib/cli/util/collectReporter.js.map
  lib/test/TestCollector.js
  lib/test/TestCollector.js.map
  lib/test/TestContext.d.ts.map
  lib/test/TestContext.js
  lib/test/TestContext.js.map
  lib/test/TestGroup.d.ts
  lib/test/TestGroup.d.ts.map
  lib/test/TestGroup.js
  lib/test/TestGroup.js.map
  src/cli/util/collectReporter.ts
  src/test/TestCollector.ts
  src/test/TestContext.ts
  src/test/TestGroup.ts
Labels: enhancement

#102 [Bugfix] use getString(pointer, defaultValue) helper method
  src/test/TestCollector.ts
Labels: bug, completed

#100 [Feature] Cleanup log output, add simple log warnings
  src/cli/init.ts
  src/cli/run.ts
  src/cli/types.ts
Labels: enhancement

#104 Massive Test Refactor
  __tests__/TestContext.log.spec.ts
  __tests__/TestContext.pass-fail.spec.ts
  __tests__/TestContext.performance.spec.ts
  __tests__/TestContext.spec.ts.old
  __tests__/__snapshots__/TestContext.log.spec.ts.snap
  __tests__/__snapshots__/TestContext.pass-fail.spec.ts.snap
  __tests__/__snapshots__/TestContext.performance.spec.ts.snap
  __tests__/setup/createLogModule.ts
  __tests__/setup/createPassFailModule.ts
  __tests__/setup/createPerformanceModule.ts
  assembly/__tests__/RTrace.spec.wat
  assembly/__tests__/addedFiles.spec.wat
  assembly/__tests__/customImports.spec.wat
  assembly/__tests__/empty.spec.wat
  assembly/__tests__/emptyDescribeBlock.spec.wat
  assembly/__tests__/flow.spec.wat
  assembly/__tests__/greaterThan.spec.wat
  assembly/__tests__/greaterThanOrEqualTo.spec.wat
  assembly/__tests__/lessThan.spec.wat
  assembly/__tests__/lessThanOrEqualTo.spec.wat
  assembly/__tests__/logs.spec.wat
  assembly/__tests__/nested-describe.spec.wat
  assembly/__tests__/performance.spec.wat
  assembly/__tests__/toBe.spec.wat
  assembly/__tests__/toBeCloseTo.spec.wat
  assembly/__tests__/toBeFalsy.spec.wat
  assembly/__tests__/toBeFinite.spec.wat
  assembly/__tests__/toBeNaN.spec.wat
  assembly/__tests__/toBeNull.spec.wat
  assembly/__tests__/toBeTruthy.spec.wat
  assembly/__tests__/toHaveLength.spec.wat
  assembly/__tests__/toInclude.spec.wat
  assembly/__tests__/toIncludeEqual.spec.wat
  assembly/__tests__/toStrictEqual.spec.wat
  assembly/__tests__/unit.spec.wat
  assembly/__tests__/unreachable.spec.wat
  assembly/jest-log.ts
  assembly/jest-pass-fail.ts
  assembly/jest-performance.ts
  assembly/jest.ts
  src/test/TestCollector.ts
  src/test/TestContext.ts
Labels: completed, enhancement

#99 [WIP] Arg Parser
  __tests__/IYargs.spec.ts
  __tests__/PerformanceConfiguration.spec.ts
  package-lock.json
  package.json
  src/cli/help.ts
  src/cli/index.ts
  src/cli/run.ts
  src/cli/util/IYargs.ts
  src/cli/util/asciiArt.ts
  src/cli/util/collectPerformanceConfiguration.ts
  src/cli/util/collectReporter.ts
  src/cli/util/getTestEntryFiles.ts
  src/cli/util/strings.ts
  src/test/TestCollector.ts
  src/test/TestContext.ts
  src/util/IAspectExports.ts
  src/util/IConfiguration.ts
  src/util/IPerformanceConfiguration.ts
Labels: enhancement
