Repository jtenner/as-pect, pull requests merged in 2020-02, with the labels that each got.

#215 add isManaged, handle unmanaged classes
  packages/assembly/assembly/__tests__/RTrace.spec.wat
  packages/assembly/assembly/__tests__/addedFiles.spec.wat
  packages/assembly/assembly/__tests__/customImports.spec.wat
  packages/assembly/assembly/__tests__/greaterThan.spec.wat
  packages/assembly/assembly/__tests__/greaterThanOrEqualTo.spec.wat
  packages/assembly/assembly/__tests__/lessThan.spec.wat
  packages/assembly/assembly/__tests__/lessThanOrEqualTo.spec.wat
  packages/assembly/assembly/__tests__/logs.spec.ts
  packages/assembly/assembly/__tests__/logs.spec.wat
  packages/assembly/assembly/__tests__/nested-describe.spec.wat
  packages/assembly/assembly/__tests__/performance.spec.wat
  packages/assembly/assembly/__tests__/toBe.spec.wat
  packages/assembly/assembly/__tests__/toBeCloseTo.spec.wat
  packages/assembly/assembly/__tests__/toBeFalsy.spec.wat
  packages/assembly/assembly/__tests__/toBeFinite.spec.wat
  packages/assembly/assembly/__tests__/toBeNaN.spec.wat
  packages/assembly/assembly/__tests__/toBeNull.spec.wat
  packages/assembly/assembly/__tests__/toBeTruthy.spec.wat
  packages/assembly/assembly/__tests__/toHaveLength.spec.wat
  packages/assembly/assembly/__tests__/toInclude.spec.wat
  packages/assembly/assembly/__tests__/toIncludeEqual.spec.wat
  packages/assembly/assembly/__tests__/toStrictEqual.spec.wat
  packages/assembly/assembly/__tests__/unreachable.spec.wat
  packages/assembly/assembly/internal/Reflect.ts
  packages/core/__tests__/__snapshots__/TestContext.log.spec.ts.snap
  packages/core/__tests__/__snapshots__/TestContext.pass-fail.spec.ts.snap
  packages/core/assembly/jest-log.ts
  packages/core/lib/as-pect.core.amd.d.ts
  packages/core/lib/as-pect.core.amd.d.ts.map
  packages/core/lib/as-pect.core.amd.js
  packages/core/lib/test/TestCollector.js
  packages/core/lib/util/HostValue.d.ts
  packages/core/lib/util/HostValue.js
  packages/core/src/test/TestCollector.ts
  packages/core/src/util/HostValue.ts
Labels: Bug :bug:, Enhancement :palm_tree:

#221 Create npm script to update snapshots
  package-lock.json
  package.json
  packages/assembly/package.json
  packages/cli/lib/as-pect.cli.amd.d.ts.map
  packages/cli/lib/as-pect.cli.amd.js
  packages/cli/lib/run.js
  packages/cli/package.json
  packages/cli/src/run.ts
  packages/core/README.md
  packages/core/__tests__/setup/createInvalidExpectationModule.ts
  packages/core/__tests__/setup/createLogModule.ts
  packages/core/__tests__/setup/createPassFailModule.ts
  packages/core/__tests__/setup/createPerformanceConfigurationModule.ts
  packages/core/__tests__/setup/createPerformanceModule.ts
  packages/core/__tests__/setup/createRTraceModule.ts
  packages/core/__tests__/setup/createTestGroupFilterModule.ts
  packages/core/lib/as-pect.core.amd.d.ts
  packages/core/lib/as-pect.core.amd.d.ts.map
  packages/core/lib/as-pect.core.amd.js
  packages/core/lib/test/TestCollector.js
  packages/core/lib/transform/createAddHostValueKeyValuePairsMember.js
  packages/core/lib/transform/createGenericTypeParameter.js
  packages/core/lib/transform/createStrictEqualsMember.js
  packages/core/lib/transform/emptyTransformer.js
  packages/core/lib/transform/index.d.ts
  packages/core/lib/transform/index.js
  packages/core/package.json
  packages/core/src/test/TestCollector.ts
  packages/core/src/transform/createAddHostValueKeyValuePairsMember.ts
  packages/core/src/transform/createGenericTypeParameter.ts
  packages/core/src/transform/createStrictEqualsMember.ts
  packages/core/src/transform/emptyTransformer.ts
  packages/core/src/transform/index.ts
Labels: Enhancement :palm_tree:

#236 Log error and exit if there are no files of matching pattern
  packages/cli/lib/as-pect.cli.amd.d.ts.map
  packages/cli/lib/as-pect.cli.amd.js
  packages/cli/lib/as-pect.cli.amd.js.map
  packages/cli/lib/run.d.ts.map
  packages/cli/lib/run.js
  packages/cli/lib/run.js.map
  packages/cli/src/run.ts
Labels: Completed :+1:, Enhancement :palm_tree:

#241 Snapshot reporters output
  packages/assembly/README.md
  packages/assembly/as-pect.config.js
  packages/assembly/assembly/__tests__/RTrace.spec.wat
  packages/assembly/assembly/__tests__/addedFiles.spec.wat
  packages/assembly/assembly/__tests__/customImports.spec.wat
  packages/assembly/assembly/__tests__/nested-describe.spec.wat
  packages/assembly/assembly/__tests__/toBe.spec.wat
  packages/assembly/assembly/__tests__/toStrictEqual.spec.wat
  packages/assembly/assembly/__tests__/unreachable.spec.wat
  packages/assembly/assembly/internal/Expectation.ts
  packages/core/__tests__/SummaryReporter.spec.ts
  packages/core/__tests__/VerboseReporter.spec.ts
  packages/core/__tests__/__snapshots__/SummaryReporter.spec.ts.snap
  packages/core/__tests__/__snapshots__/TestContext.pass-fail.spec.ts.snap
  packages/core/__tests__/__snapshots__/VerboseReporter.spec.ts.snap
  packages/core/__tests__/setup/createReporterModule.ts
  packages/core/assembly/index.ts
  packages/core/assembly/jest-reporter.ts
  packages/core/assembly/jest-reporter2.ts
  packages/core/assembly/jest-reporter3.ts
  packages/core/assembly/tsconfig.json
  packages/core/jest.config.js
  packages/core/package.json
  packages/core/src/reporter/SummaryReporter.ts
  packages/core/src/reporter/VerboseReporter.ts
  packages/core/src/test/TestCollector.ts
Labels: Bug :bug:, Completed :+1:, Enhancement :palm_tree:

#244 Support instantiation of module from config
  package-lock.json
  packages/assembly/assembly/__tests__/instantiateImports.spec.imports.js
  packages/assembly/assembly/__tests__/instantiateImports.spec.ts
  packages/assembly/assembly/__tests__/instantiateImports.spec.wat
  packages/cli/src/run.ts
  packages/core/src/test/TestCollector.ts
Labels: Breaking Change :boom:, Enhancement :palm_tree:

#245 remove dev dependencies to speed up bootstrapping
  package-lock.json
  package.json
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/core/package-lock.json
  packages/core/package.json
Labels: Enhancement :palm_tree:

#248 Implement IReporter on json and csv reporters
  README.md
  packages/assembly/README.md
  packages/cli/README.md
  packages/core/README.md
  packages/core/src/test/TestNode.ts
  packages/csv-reporter/index.ts
  packages/csv-reporter/readme.md
  packages/json-reporter/index.ts
  packages/json-reporter/readme.md
Labels: Enhancement :palm_tree:
