Repository jtenner/as-pect, pull requests merged in 2020-03, with the labels that each got.

#258 switch to commonjs
  packages/cli/tsconfig.json
  packages/core/tsconfig.json
  packages/csv-reporter/tsconfig.json
  packages/json-reporter/tsconfig.json
Labels: Breaking Change :boom:, Enhancement :palm_tree:

#262 feature traverse namespaces
  packages/assembly/assembly/__tests__/logs.spec.ts
  packages/assembly/assembly/__tests__/logs.spec.wat
  packages/core/src/transform/index.ts
Labels: Bug :bug:, Enhancement :palm_tree:

#263 fix strictEquality for private members
  packages/assembly/assembly/__tests__/toStrictEqual.spec.ts
  packages/assembly/assembly/__tests__/toStrictEqual.spec.wat
  packages/assembly/assembly/internal/Reflect.ts
  packages/core/src/transform/createAddReflectedValueKeyValuePairsMember.ts
  packages/core/src/transform/createStrictEqualsMember.ts
  packages/core/src/transform/hash.ts
Labels: Bug :bug:, Completed :+1:

#256 Add lerna badge
  README.md
  packages/assembly/README.md
  packages/cli/README.md
  packages/core/README.md
  packages/csv-reporter/readme.md
  packages/json-reporter/readme.md
Labels: Docs 📜

#268 Implement warning that object serializes to same value in toBe assertions
  packages/assembly/assembly/__tests__/RTrace.spec.wat
  packages/assembly/assembly/__tests__/addedFiles.spec.wat
  packages/assembly/assembly/__tests__/customImports.spec.wat
  packages/assembly/assembly/__tests__/instantiateImports.spec.wat
  packages/assembly/assembly/__tests__/nested-describe.spec.wat
  packages/assembly/assembly/__tests__/toBe.spec.wat
  packages/assembly/assembly/__tests__/toStrictEqual.spec.wat
  packages/assembly/assembly/__tests__/unreachable.spec.wat
  packages/assembly/assembly/internal/Expectation.ts
  packages/core/__tests__/__snapshots__/SummaryReporter.fail.spec.ts.snap
  packages/core/__tests__/__snapshots__/TestContext.pass-fail.spec.ts.snap
  packages/core/__tests__/__snapshots__/VerboseReporter.fail.spec.ts.snap
  packages/core/__tests__/__snapshots__/VerboseReporter.pass.spec.ts.snap
  packages/core/assembly/jest-reporter-fail.ts
  packages/core/src/reporter/SummaryReporter.ts
Labels: Completed :+1:, Enhancement :palm_tree:

#267 Strict Equality for ArrayLike
  package-lock.json
  packages/assembly/assembly/__tests__/toStrictEqual.spec.ts
  packages/assembly/assembly/__tests__/toStrictEqual.spec.wat
  packages/assembly/assembly/internal/Reflect.ts
Labels: Bug :bug:, Completed :+1:

#270 fix nullable reflected references
  packages/assembly/assembly/__tests__/toBe.spec.wat
  packages/assembly/assembly/__tests__/toIncludeEqual.spec.wat
  packages/assembly/assembly/__tests__/toStrictEqual.spec.ts
  packages/assembly/assembly/__tests__/toStrictEqual.spec.wat
  packages/assembly/assembly/internal/Expectation.ts
  packages/assembly/assembly/internal/Reflect.ts
  packages/core/__tests__/__snapshots__/SummaryReporter.fail.spec.ts.snap
  packages/core/__tests__/__snapshots__/TestContext.pass-fail.spec.ts.snap
  packages/core/__tests__/__snapshots__/VerboseReporter.fail.spec.ts.snap
  packages/core/assembly/jest-reporter-fail.ts
Labels: Bug :bug:

#274 WASI support
  package-lock.json
  packages/cli/src/index.ts
  packages/cli/src/run.ts
  packages/cli/src/util/AspectConfiguration.ts
  packages/core/src/test/TestContext.ts
Labels: Enhancement :palm_tree:
