Repository jtenner/as-pect, pull requests merged in 2020-05, with the labels that each got.

#287 update packages
  package-lock.json
  package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/test/TestContext.ts
  packages/csv-reporter/package-lock.json
  packages/csv-reporter/package.json
  packages/snapshots/package-lock.json
  packages/snapshots/package.json
  packages/snapshots/src/parser/grammar.ts
Labels: Breaking Change :boom:

#288 remove isDefined for unchecked, code coverage problem, long.js usage
  packages/assembly/assembly/__tests__/toBe.spec.wat
  packages/assembly/assembly/__tests__/toStrictEqual.spec.wat
  packages/assembly/assembly/internal/Reflect.ts
  packages/core/__tests__/__snapshots__/SummaryReporter.fail.spec.ts.snap
  packages/core/__tests__/__snapshots__/TestContext.log.spec.ts.snap
  packages/core/__tests__/__snapshots__/TestContext.pass-fail.spec.ts.snap
  packages/core/__tests__/__snapshots__/VerboseReporter.fail.spec.ts.snap
  packages/core/__tests__/__snapshots__/VerboseReporter.pass.spec.ts.snap
  packages/core/__tests__/__snapshots__/VerboseReporter.snapshot.spec.ts.snap
  packages/core/__tests__/setup/SummaryReporterWrapper.ts
  packages/core/__tests__/setup/VerboseReporterWrapper.ts
  packages/core/__tests__/setup/removeStackTraces.ts
  packages/core/src/test/TestContext.ts
Labels: Bug :bug:, Completed :+1:, Enhancement :palm_tree:

#289 Long.fromBits fix, prettier
  packages/core/__tests__/__snapshots__/TestContext.pass-fail.spec.ts.snap
  packages/core/src/test/TestContext.ts
Labels: Bug :bug:, Completed :+1:

#296 Fix toHaveLength, update packages
  package-lock.json
  packages/assembly/assembly/__tests__/toHaveLength.spec.wat
  packages/assembly/assembly/internal/Expectation.ts
  packages/core/__tests__/__snapshots__/TestContext.pass-fail.spec.ts.snap
  packages/core/assembly/jest-pass-fail.ts
Labels: Bug :bug:, Completed :+1:

#290 General Cleanups
  packages/assembly/assembly/__tests__/lessThan.spec.wat
  packages/assembly/assembly/__tests__/toBeNull.spec.wat
  packages/assembly/assembly/__tests__/toBeTruthy.spec.wat
  packages/assembly/assembly/internal/Expectation.ts
Labels: Enhancement :palm_tree:

#299 Increase verbose reporter expand depth
  packages/core/src/reporter/VerboseReporter.ts
  packages/core/src/util/stringifyReflectedValue.ts
Labels: Completed :+1:, Enhancement :palm_tree:

#300 Redo asp bin to use spawn()
  packages/cli/bin/asp
Labels: Bug :bug:
